[workspace]
    members = ["axum-static", "examples/*"]
    default-members = ["axum-static"]
    resolver = "3"

[dependencies]
    axum = "0.8.6"
    tower-http = { version = "0.6.6", features = ["fs"] }
